### ISSUE TITLE
cmake finds incorrect include directory when SystemC is installed in a directory called systemc

### ISSUE THREAD

**Issue by rstemmer** [offis/libtvs#7]
There is a problem building libtvs with SystemC support.
The include path gets not determined correctly.

Problem
--------
When SystemC got installed in a directory called "systemc", then the include path for SystemC determined by cmake is wrong.
For example, if SystemC got installed to /opt/systemc, then cmake determines "/opt" as include directory. Correct would be "/opt/systemc/include".

The problem is the `find_path` call in [FindSystemC.cmake line 24](https://github.com/offis/libtvs/blob/develop/cmake/modules/FindSystemC.cmake#L24)

Steps to reproduce error
--------

1. Install SystemC into a directory called `systemc` (Sym-Link may work as well, did not test it.)
2. Follow libtvs build instruction until entering the new created build directory
3. `export SYSTEMC_HOME=/opt/systemc` or similar
4. `cmake ..`
5. `cmake --build .` An error occures for a line `#include <systemc>` telling that systemc cannot be found:

```
[  6%] Building CXX object src/CMakeFiles/tvs.dir/units/common_impl.cpp.o
In Datei, eingebunden von /home/ralf/git/libtvs/include/tvs/utils/variant_traits.h:21,
von /home/ralf/git/libtvs/src/units/common_impl.cpp:20:
/home/ralf/git/libtvs/include/tvs/utils/systemc.h:29:10: schwerwiegender Fehler: systemc: Datei oder Verzeichnis nicht gefunden
   29 | #include <systemc>
```

Following these steps and adding `Include at ${SYSTEMC_INCLUDE_DIR}` to the message in [FindSystemC.cmake line 51](https://github.com/offis/libtvs/blob/develop/cmake/modules/FindSystemC.cmake#L51) reveals the wrong determined include path.

Workaround
--------
Change [line 24](https://github.com/offis/libtvs/blob/develop/cmake/modules/FindSystemC.cmake#L24) by adding a .h as file extension to systemc.
This works for all SystemC versions that have a header "systemc.h" beside the header "systemc".

**Original:**
```cmake
  find_path (SYSTEMC_INCLUDE_DIR systemc
    PATH_SUFFIXES include
    PATHS ${SYSTEMC_SEARCH_PATH}
    )
```

**Workaround:**
```cmake
  find_path (SYSTEMC_INCLUDE_DIR systemc.h
    PATH_SUFFIXES include
    PATHS ${SYSTEMC_SEARCH_PATH}
    )
```

Using `find_file` instead of `find_path` does not work as well. In that case, /opt/systemc gets identified as include director which is also wrong.

Details
------

- SystemC 2.3.2 installed at /opt/systemc
- cmake version 3.17.0 (x86.64)
- GCC 9.3.0

**Comment by pitti** [comment]
Thanks for the report! Indeed, `cmake` seems to accept a directory as a valid search result when calling `find_file()`. The reason why the directory `/opt/systemc` is accepted before the path given in PATHS is searched seems to be that PATHS is appended at the very end of the search list.

However, I don't consider the proposed solution to be future-proof, since the IEEE 1666-2011 SystemC LRM states (5.1.2 #include "systemc.h"):
> The header file systemc.h is provided for backward compatibility with earlier versions of SystemC and may be deprecated in future versions of this standard.

Using HINTS instead of PATHS solves the problem by prepending the custom path to the search list.
